name: mreserve
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ffmpeg=4.3
  - ffprobe=4.3
  - tqdm
  - numpy
  - pyyaml
  - scipy
  - ipython
  - cython
  - typing
  - h5py
  - pandas
  - matplotlib
  - pip
  - pip:
    - jax
    - jaxlib
    - numpy==1.21.1
    - youtube-dl==2021.6.6
    - tensorflow>=2.6.0
    - clu==0.0.6
    - fabric==2.6.0
    - tqdm
    - optax==0.0.9
    - aioredis==1.3.1
    - pandas==1.3.0
    - google-cloud-storage==1.40.0
    - regex==2021.7.6
    - scipy==1.7.0
    - librosa==0.8.1
    - glob2==0.6
    - beautifulsoup4==4.10.0
    - ftfy==6.0.3
    - scikit-video==1.1.11
    - numba==0.53.1
    - tokenizers==0.10.3
    - Flask==2.0.2
    - Flask-Cors==3.0.10
    - gevent==21.8.0
    - flax==0.3.4
    - lxml
    - tensorflow-datasets==4.4.0
    - transformers==4.8.2
    - tensorflow==2.7.1
    - torch
    - protobuf==3.20.1
